### ISSUE TITLE
운동카드 CRUD

### ISSUE THREAD

**Issue by LeeGeonwoo22** [codestates/rouDDine-server#11]
### ISSUE
- Group:  `server`
- Type: `feature`,
- Detail: 운동카드 CRUD구현하기. 

### TODO
1. [ ] 개인 운동루틴 생성
2. [ ] 개인 운동루틴 조회
2. [ ] 개인 운동루틴 업데이트
3. [ ] 개인 운동루틴 삭제

### Estimated time
> Pick one
`3h`

### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint 1`
- Urgency: `High`
